name: Fojin site testing

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v3.0.0
      - name: Install plugin
        run: pip install pytest-github-actions-annotate-failures
      - name: Test with PyTest
        run: |
          pytest --browser chrome_headless
      - name: Allure report
        uses: vadim-makarov/allure-report-action@main
        if: always()
        id: allure-report
        with:
          allure-results: allure-results
          allure-report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: vadim-makarov/actions-gh-pages@main
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
