name: Fojin site testing

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Starting Selenoid Server
        uses: ajinx/selenoid@2.0
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Python Dependency Installation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install plugin
        run: pip install pytest-github-actions-annotate-failures
      - name: Test with PyTest
        run: |
          pytest
      - name: Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        continue-on-error: true
        id: allure_report
        with:
          allure-results: allure_results
          gh_pages: gh-pages
          allure-report: allure_report
          allure_history: allure_history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh_pages
          PUBLISH_DIR: allure_history
